version: "3"
services:
  schedulerbot:
    container_name: schedulerbot
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '5001:5000'
    volumes:
      - data:/app/data
    env_file:
      - ./.env

volumes:
  data: